### ISSUE TITLE
Add Class names

### ISSUE THREAD

**Issue by mmailaender** [yet3/figma-svg-to-react#1]
It would be great if there would be an option to remove all fill & strokes and instead adding class names for <svg>, <g>, <path> etc. elements based on the Figma element naming.

**Comment by yet3** [comment]
An option to remove fill/stroke attributes sounds nice. I'm not sure if I properly understand what you mean by adding class names based on elements' names.

Something like this? (let's say the icon's name is ArrowDownIcon)
**Before**
```html
<svg width={100} height={100}>
  <rect fill='red' x={0} y={0} width={40} height={40}  />
  <circle fill='purple' stroke='yellow' cx={40} cy={40} r={20} />
</svg>
```

**After**
```html
<svg width={100} height={100} className='arrowDownIcon'>
  <rect x={0} y={0} width={40} height={40}  />
  <circle cx={40} cy={40} r={20} />
</svg>
```
