### ISSUE TITLE
Number in Name - React

### ISSUE THREAD

**Issue by jayliu50** [yet3/figma-svg-to-react#7]
Wow! A huge refresh! Thank you for your continued work on this plugin! 

---

I had a bug to report.

I encountered it when running the React tab.

When there is a number or special chars in the name, it just gets dropped. 

This is problematic because I could have `icons/video-1` and `icons/video-2` and they would both become components named `IconsVideo` which would cause issues if I'm importing them into code.

See this screenshot, which tells all.

![{E10AFE71-5192-4262-B030-59ED0F5F4B27}](https://github.com/user-attachments/assets/09c66ef0-31ab-44f4-83be-ccb073ea5be0)

In the screenshot above, I would have expected `Icons/video-2` to generate a file name and component name `IconsVideo2` NOT `IconsVideo`.

**Comment by yet3** [comment]
fixed in #13, will be released with #12
