### ISSUE TITLE
className for React exports

### ISSUE THREAD

**Issue by jayliu50** [yet3/figma-svg-to-react#8]
Do you intend on restoring the `className`?

This was helpful because when I named icons `Icons/A` `Icons/B` `Icons/C`, I could write a css rule for `svg[class^='Icons']` that only affects the icons.

**Comment by yet3** [comment]
In this case, I admit I somehow missed it completely while rewriting the plugin, I will also add it back.
Thank you for opening this issue.

**Comment by jayliu50** [comment]
No worries! Seems like quite the undertaking. Thank you for your work!

**Comment by yet3** [comment]
added in #14, and I also just released it, so all the fixes are live.
If there is anything else let me now, and again thank you for reporting the issues :+1:
